# fly.toml app configuration file generated for ctsmesh-web on 2024-06-17T17:06:39+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ctsmesh-web'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
